services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projectx
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  dbadmin:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080

  authservice:
    image: authservice
    container_name: authservice
    build:
      context: ./backend/auth
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

volumes:
  pgdata: